# GitHub Actions workflow for ParaBank Website Testing with Cypress
# Place this file in .github/workflows/dev-tests.yml
name: ParaBank Dev Tests
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:  # Allows manual triggering
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Cypress run
        run: npm run cypress:run
      - name: Upload Cypress screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
  # This job is useful for development purposes but typically skipped in CI
  # It's included here for completeness but commented out
  cypress-open:
    runs-on: ubuntu-latest
    if: false  # This conditionally disables this job in CI
    timeout-minutes: 30
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Cypress open
        run: npm run cypress:open
